### ISSUE TITLE
Extension completamente en blanco

### ISSUE THREAD

**Issue by peya02** [intelequia/dnn.powerbiembedded#6]
Hola,
he añadido dnn.powerbiembedded a mi dnn pero no me aparece nada, completamente en blanco. 
¿sabeis que puede estar pasando?
Adjunto captura de como esta.
![powerbiembedded](https://user-images.githubusercontent.com/102723946/191896510-eb7361e9-7d7f-433f-9000-a9790a9ceceb.png)

**Comment by davidjrh** [comment]
Buenas, este error parece el mismo que fue detectado en el proveedor de Azure AD B2C https://github.com/intelequia/dnn.azureadb2cprovider/issues/30, en el que parece que hay un bug al cargar la persona bar si se usa un "child portal alias" (ruta <servername>/<portalname>) y que está pendiente de solucionar

*Workaround*: Prueba a usar un portal alias como <portalname>.dnndev.me, que también apunta a localhost y te servirá del mismo modo.

**Comment by peya02** [comment]
Parece que sigue igual, en blanco.
Cuando pones .dnndev.me (¿El punto del principio se pone?) Yo solo he puesto dnndev.me
Gracias.

**Comment by peya02** [comment]
Creo que esta parte no la entiendo muy bien “Coloqué el sitio web en el directorio raíz y funciona”
Yo actualmente tengo mi dnn en la ruta C:\WebSites\Dnns\dnn921dev
En el IIS tengo un sitio con el nombre Dnn y dos subaplicaciones donde apuntan a la ruta anterior (una dev y otra con rel)
según el comentario anterior en el sitio, de no tener nada en nombre de host, ahora tiene dnndev.me pero tampoco funciona.
Algo creo que estoy haciendo mal...
Gracias.

**Comment by peya02** [comment]
@davidjrh hola David
a ver si puedes echarme una mano con este tema por favor, me gustaría ver el funcionamiento. Muchas gracias.

**Comment by davidjrh** [comment]
Hola @peya02 
Simplemente lo que tienes que hacer es:
1. En el DNN, en el menú Site Settings > Site Behavior > Site Aliases, añadir un nuevo portal alias que se llame, por ejemplo, "misitioweb.dnndev.me" (más info en este artículo https://www.dnnsoftware.com/docs/administrators/configuring-your-site/add-site-alias.html)
2. En el IIS, crear un nuevo sitio web y que apunte a la carpeta C:\WebSites\Dnns\dnn921dev, añadiendo el binding misitioweb.dnndev.me

![image](https://user-images.githubusercontent.com/489976/192878724-d34bd9e4-7ee0-4343-a12d-03997f37fb4d.png)

Con esas dos acciones, puedes acceder por localhost/dnn921dev o directamente por misitioweb.dnndev.me. Cuando uses el segundo alias te funcionará el menú hasta que se corrija el bug comentado.

**Comment by peya02** [comment]
Hola @davidjrh,

muchas gracias, ahora si funciono. Solo un pequeño problema que no se si es genérico o solo a mi, cuando visualizo el informe, si me salen los reportes pero en algunos casos no me aparece el grafico. Sale el error; 

"Se produjo un error inesperado

Hubo un error inesperado. Pruebe otra vez más tarde.
Vuelva a intentarlo más tarde o póngase en contacto con el soporte técnico. Proporcione estos detalles si se pone en contacto con ellos."

¿Ha salido a mas gente?

Gracias.

**Comment by davidjrh** [comment]
Sí, y se me ocurren varios motivos:
* El informe está configurado para RLS (Row Level Security) y no se le está pasando la configuración correcta de RLS
* El informe usa DirectQuery y la conexión con el Gateway no está funcionando correctamente
* Se ha configurado una capacidad de Power BI Embedded y esta no está arrancada (en la última versión del módulo, debe aparecer un mensaje indicándolo)

Al hacer click en el enlace de los detalles, ¿no te da más información?

**Comment by peya02** [comment]
Hola @davidjrh 

Parece que el tema era con el RLS, tenia algunos roles creados. También estoy viendo que puedes asignar permisos a los workspace que se van creando, el problema es que cuando asigno un grupo al workspace se queda también en blanco.

![image](https://user-images.githubusercontent.com/102723946/193210425-91ac4b50-6efa-4739-9094-61b551783e8b.png)


Una vez asigno el grupo y le doy a Save, se queda en blanco y no asigna los permisos. Si vuelvo a cargar la pagina vuelve a salir como antes.

Gracias.

**Comment by peya02** [comment]
Hola @davidjrh 

También es muy raro que ahora quiero registrar otro workspace y me salta el error:

"AADSTS700016: Application with identifier 'App-Owns-Data Sample App' was not found in the directory 'GOLMAR SISTEMAS DE COMUNICACION S.A.'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant. Trace ID: e2f74f2a-e0d8-4e20-99c3-f7aca7e64800 Correlation ID: 54eaf4da-37d5-492c-8dd5-76dddd881787 Timestamp: 2022-09-30 07:28:09Z"


Lo estoy configurando con los mismos parámetros que otro que si tengo.

**Comment by peya02** [comment]
Hola @davidjrh 

por si te sirve de información, el workspace que intente crear el otro día y me dio el error anterior, finalmente si se creo. Intento agregar el modulo en una pagina pero al escoger el workspace no me muestra los informes que hay...

![image](https://user-images.githubusercontent.com/102723946/193571599-41f8f80e-f31e-41c7-a3ba-faba54997ac1.png)

Yo entiendo que el workspace esta correcto porque si voy a previsualizar, si va a mi espacio.

![image](https://user-images.githubusercontent.com/102723946/193571883-0517c7f7-d76e-4c08-93d0-beba2dc29e1b.png)

Tengo que decir, que esto funciono días atrás y no se ha hecho ningún cambio.

Lo que no me funciono es asignar permisos a un workspace para que un rol concreto pueda verlo.

Gracias.

**Comment by peya02** [comment]
Hola @davidjrh 
doy por cerrada la incidencia ya que solucione por el momento el problema.
Gracias.
